---
- debug: var=ansible_architecture
- name: Run the OS specific install tasks (failed if not supported)
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - 'install-{{ ansible_distribution }}-{{ ansible_architecture }}.yml'
        - 'install-{{ ansible_lsb.id|d(ansible_distribution) }}.yml'
        - 'install-{{ ansible_os_family }}-{{ ansible_architecture }}.yml'
