---

- fail:
    msg: You must pass the variable zabbix_common__userparameter with rule specifications
  when: zabbix_common__userparameter is not defined

- name: Ensure userparameters directory exists
  file:
    path:  '{{ zabbix_common__userparameters_directory }}'
    mode:  0755
    state: directory
  notify: [ 'restart-zabbix-agent-userparameter' ]

- name: 'Create userparameter {{ zabbix_common__userparameter.name }}'
  template:
    src:      userparameter.j2
    dest:     "{{ zabbix_common__userparameters_directory }}/{{ zabbix_common__userparameter.name }}.conf"
    owner:    root
    group:    "{{ zabbix_common__service_group|d('zabbix') }}"
    mode:     0640
  when: zabbix_common__userparameter.state|d('present') == 'present'
  notify: [ 'restart-zabbix-agent-userparameter' ]

- name: 'Remove userparameter {{ zabbix_common__userparameter.name }}'
  file:
    path:  "{{ zabbix_common__userparameters_directory }}/{{ zabbix_common__userparameter.name }}.conf"
    state: absent
  when: zabbix_common__userparameter.state|d('present') != 'present'
  notify: [ 'restart-zabbix-agent-userparameter' ]
